### ISSUE TITLE
Read Decimal from Parquet File

### ISSUE THREAD

**Issue by potter420** [jorgecarleitao/arrow2#444]
Hi,

So far we have the capability to write decimal to parquet. I wonder if we can implement reading decimal value from parquet file as well.

Thank you very much.

**Comment by potter420** [comment]
Currently, here is one of the make-shift code I made to deal with reading decimal, seem to work in my case, with a lot of non-nested decimal-having parquet data file:
```rust
use io::parquet::read::{page_iter_to_array, ParquetType, PhysicalType};
...
match metadata.descriptor().type_() {
  ParquetType::PrimitiveType { physical_type, .. } => {
      match physical_type {
          PhysicalType::Int32 => page_iter_to_array(
              &mut pages,
              metadata,
              DataType::Int32,
          )
          .map(|ar| {
              Box::new(
                  PrimitiveArray::<i128>::from_trusted_len_iter(
                      ar.as_any()
                          .downcast_ref::<PrimitiveArray<i32>>()
                          .unwrap()
                          .iter()
                          .map(|e| e.map(|e| *e as i128)),
                  )
                  .to(data_type),
              )
                  as Box<dyn Array>
          }),
          PhysicalType::Int64 => page_iter_to_array(
              &mut pages,
              metadata,
              DataType::Int64,
          )
          .map(|ar| {
              Box::new(
                  PrimitiveArray::<i128>::from_trusted_len_iter(
                      ar.as_any()
                          .downcast_ref::<PrimitiveArray<i64>>()
                          .unwrap()
                          .iter()
                          .map(|e| e.map(|e| *e as i128)),
                  )
                  .to(data_type),
              )
                  as Box<dyn Array>
          }),
          PhysicalType::FixedLenByteArray(n) => {
              page_iter_to_array(
                  &mut pages,
                  metadata,
                  DataType::FixedSizeBinary(*n),
              )
              .map(
                  |ar| {
                      let v = ar
                          .as_any()
                          .downcast_ref::<FixedSizeBinaryArray>()
                          .unwrap()
                          .iter()
                          .map(|e| {
                              e.and_then(|e| {
                                  match e
                                      .into_iter()
                                      .rev()
                                      .map(|e| *e)
                                      .pad_using(16, |_| 0u8)
                                      .rev()
                                      .collect_vec()
                                      .try_into()
                                  {
                                      Ok(v) => {
                                          Some(i128::from_be_bytes(v))
                                      }
                                      Err(_) => None,
                                  }
                              })
                          }).collect_vec();
                      Box::new(
                          PrimitiveArray::<i128>::from_trusted_len_iter(v.into_iter()).to(data_type)
                      ) as Box<dyn Array>
                  },
              )
          }
          _ => unreachable!(),
      }
  }
  _ => unreachable!(),
},
```

**Comment by jorgecarleitao** [comment]
That snipped seems correct!

I would add one roundtrip test on `tests/it/io/parquet/write` per physical type, and a test to read parquet written by `pyarrow`, so that we verify that the assumptions about the format hold on our reader.

Let me know if you would like to work on this or if you would like me to take it =)

**Comment by potter420** [comment]
Hello, sorry for the late reply, been a busy week. I would take this one, including the tests. 
Just to be sure, we would write a test which include 3 type of physical decimal, according the write code, that should be:
- A decimal with precision not greater than 9 (int32), 18 (int64) and 26 (fix length bytes, I just pick a random number greater than 19 here)
And a parquet written by `pyarrow`, which similar columns above. How should we generate the `pyarrow` files for the test tho?

**Comment by jorgecarleitao** [comment]
Hey @potter420 , no worries. Exactly, so that we demonstrate interoperability with the 3 physical types.

We have a script [here](https://github.com/jorgecarleitao/arrow2/blob/main/parquet_integration/write_parquet.py) where we generate parquet files as part of the tests. The data placed there is then replicated [around here](https://github.com/jorgecarleitao/arrow2/blob/main/tests/it/io/parquet/mod.rs#L175), which are compared in tests such as [this one](https://github.com/jorgecarleitao/arrow2/blob/main/tests/it/io/parquet/read.rs#L126).

So, something like

1. add new fields to nullable and required in the `.py` linked above
2. add the corresponding data to the `.rs` file linked above
3. add the test targeting the new columns to the `.rs` file linked above

Note that we also test statistics, so those are also needed.

**Comment by jorgecarleitao** [comment]
Ah, for testing out locally, I usually create a venv as we do it in the CI [here](https://github.com/jorgecarleitao/arrow2/blob/main/.github/workflows/test.yml#L17)

**Comment by potter420** [comment]
Hmm, my test failed miserably. According to `pyarrow` output:
```
<pyarrow._parquet.ColumnChunkMetaData object at 0x7f4159b5adb0>
  file_offset: 2400
  file_path: 
  physical_type: FIXED_LEN_BYTE_ARRAY
  num_values: 10
  path_in_schema: decimal_9
  is_stats_set: True
  statistics:
    <pyarrow._parquet.Statistics object at 0x7f4159b5aea0>
      has_min_max: True
      min: b'\x00\x00\x00\x00'
      max: b'\x00\x00\x00\t'
      null_count: 3
      distinct_count: 0
      num_values: 7
      physical_type: FIXED_LEN_BYTE_ARRAY
      logical_type: Decimal(precision=9, scale=0)
      converted_type (legacy): DECIMAL
  compression: UNCOMPRESSED
  encodings: ('PLAIN', 'RLE')
  has_dictionary_page: False
  dictionary_page_offset: None
  data_page_offset: 2320
  total_compressed_size: 80
  total_uncompressed_size: 80
```
Seem like we have to implement FIXED_LEN_BYTE_ARRAY statistics as well, or perhaps I can set statistics to null for the moments?
